use `Optional[Literal['utf-8']]` type hint for FileType encoding kwarg
instead of unpacking kwargs with mypy errors:
lark\tools\__init__.py:26: error: Argument 2 to "FileType" has incompatible type "**Dict[str, str]"; expected "int"  [arg-type]
lark\tools\__init__.py:27: error: Argument 2 to "FileType" has incompatible type "**Dict[str, str]"; expected "int"  [arg-type]