explicitly check for `str` instance instead of relying on else alone
Explicit is better than implicit.
This also helps to get rid of two mypy errors:
lark\tools\__init__.py:34: error: Argument 1 to "append" of "list" has incompatible type "Sequence[str]"; expected "str"  [arg-type]
lark\tools\__init__.py:35: error: Unsupported operand types for + ("str" and "Sequence[str]")  [operator]