Remove package `lark-stubs` from `setup.py`
The package was removed in PR lark-parser/lark#926.  When trying to
install lark upstream, pip fails:

> error: package directory 'lark-stubs' does not exist